"""empty message

Revision ID: 496743d60a86
Revises: eb5a408236f4
Create Date: 2018-10-13 15:04:50.875328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496743d60a86'
down_revision = 'eb5a408236f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alunos', sa.Column('cod_student', sa.Integer(), nullable=False))
    op.alter_column('alunos', 'created',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_unique_constraint(None, 'alunos', ['cod_student'])
    op.add_column('cursos', sa.Column('cod_course', sa.String(length=6), nullable=False))
    op.alter_column('cursos', 'created',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_unique_constraint(None, 'cursos', ['cod_course'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cursos', type_='unique')
    op.alter_column('cursos', 'created',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_column('cursos', 'cod_course')
    op.drop_constraint(None, 'alunos', type_='unique')
    op.alter_column('alunos', 'created',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_column('alunos', 'cod_student')
    # ### end Alembic commands ###
