"""empty message

Revision ID: eb5a408236f4
Revises: e0e076590022
Create Date: 2018-10-12 23:12:15.594234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb5a408236f4'
down_revision = 'e0e076590022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telefone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('phone', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('telefone')
    # ### end Alembic commands ###
